### ISSUE TITLE
`chatengine` crash during `make`

### ISSUE THREAD

**Issue by tattwamasii2p** [i2pgram/i2pgram#2]
```
sudo make -j7
docker build -t chatengine/server:latest .
docker-compose up -d
Pulling redis (redis:5.0.0-alpine3.8)...
5.0.0-alpine3.8: Pulling from library/redis
4fe2ade4980c: Pull complete
fb758dc2e038: Pull complete
989f7b0c858b: Pull complete
9d8bd3a94284: Pull complete
997d9e740b77: Pull complete
d76bc130a47a: Pull complete
Digest: sha256:6a9540142534c63da7aec6137b68ecc888d1505aecfc83755c579a97dc4330fe
Status: Downloaded newer image for redis:5.0.0-alpine3.8
Pulling etcd (appcelerator/etcd:3.3.3)...
3.3.3: Pulling from appcelerator/etcd
ff3a5c916c92: Pull complete
2b4ee2a9522c: Pull complete
6adcc641702b: Pull complete
4c5fb43c0f32: Pull complete
ac201bb5fccd: Pull complete
fc2ca4981e50: Pull complete
Digest: sha256:22abb05bc6f1b7eac7141274469902366265017f7a41902a573e28f719e3ac6a
Status: Downloaded newer image for appcelerator/etcd:3.3.3
Pulling mysql (mysql:5.7.17)...
5.7.17: Pulling from library/mysql
6d827a3ef358: Pulling fs layer
ed0929eb7dfe: Pulling fs layer
03f348dc3b9d: Pulling fs layer
fd337761ca76: Waiting
7e6cc16d464a: Pulling fs layer
ca3d380bc018: Pulling fs layer
3fe11378d5c0: Waiting
2b5dfd325645: Waiting
b54281d17fbe: Waiting
7eae4db8eea5: Waiting
76cf68e17b09: Waiting
double free or corruption (out)
SIGABRT: abort
PC=0x7fd5bf461fb7 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc42004dcc0, 0xc42004dce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc42004dc90 sp=0xc42004dc50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xc48920)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc42004dcc0 sp=0xc42004dc90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xc48920)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc42004dcf8 sp=0xc42004dcc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200143e0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc42004dda0 sp=0xc42004dcf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc42004de88, 0x410022, 0xc420014330)
	<autogenerated>:4 +0x46 fp=0xc42004dde0 sp=0xc42004dda0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc42004de68 sp=0xc42004dde0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffdfc8ee807, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc42004ded8 sp=0xc42004de68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc42004df58 sp=0xc42004ded8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc42004df88 sp=0xc42004df58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc42004dfe0 sp=0xc42004df88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42004dfe8 sp=0xc42004dfe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffdfc8ecd20
rcx    0x7fd5bf461fb7
rdx    0x0
rdi    0x2
rsi    0x7ffdfc8ecab0
rbp    0x7ffdfc8ece20
rsp    0x7ffdfc8ecab0
r8     0x0
r9     0x7ffdfc8ecab0
r10    0x8
r11    0x246
```

**Comment by tattwamasii2p** [comment]
I did `sudo dpkg -r --force-depends golang-docker-credential-helpers` as the anwer https://stackoverflow.com/a/57243027/529442 specifies, and this fixed this crash. We'll see if this breaks subsequent phases.

**Comment by asmexcaliburwoods** [comment]
See also: https://www.google.com/search?channel=fs&client=ubuntu&q=sigabrt+%2Fusr%2Flib%2Fgo-1.8%2Fsrc%2Fruntime%2Fasm_amd64.s%3A2197
